# Generated by Django 2.2 on 2021-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidingimage',
            old_name='Button',
            new_name='button',
        ),
        migrations.RenameField(
            model_name='slidingimage',
            old_name='Image',
            new_name='image',
        ),
        migrations.AddField(
            model_name='slidingimage',
            name='button_hyperlink',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
