# Generated by Django 2.2 on 2021-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_auto_20210523_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(blank=True, max_length=100)),
                ('title', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
