# Generated by Django 2.2 on 2021-05-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_quantity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity_title',
            name='quantity',
        ),
    ]
