# Generated by Django 2.2 on 2021-05-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_remove_quantity_title_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity_title',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
