# Generated by Django 2.2 on 2021-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_auto_20210523_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_title',
            name='quantity',
            field=models.IntegerField(max_length=50),
        ),
    ]
