# Generated by Django 2.2 on 2021-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_auto_20210523_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_title',
            name='quantity',
            field=models.TextField(max_length=50),
        ),
    ]
