# Generated by Django 2.2 on 2021-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0008_auto_20210523_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_title',
            name='quantity',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
