# Generated by Django 2.2 on 2021-05-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0009_auto_20210523_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity_title',
            name='quantity',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
