# Generated by Django 2.2 on 2021-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_auto_20210523_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apk_Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/home')),
                ('aplication_areas', models.TextField(blank=True, max_length=100)),
                ('field', models.TextField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
