# Generated by Django 2.2 on 2021-05-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0011_apk_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apk_areas',
            name='is_available',
        ),
    ]
