# Generated by Django 2.2 on 2021-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0012_remove_apk_areas_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=100)),
            ],
        ),
    ]
