# Generated by Django 2.2 on 2021-05-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_media_coverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_Sliding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='photos/home')),
                ('date', models.TextField(max_length=100)),
                ('title', models.TextField(max_length=150)),
                ('know_more', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
