# Generated by Django 2.2 on 2021-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0014_media_sliding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_sliding',
            name='date',
            field=models.IntegerField(max_length=100),
        ),
    ]
