# Generated by Django 2.2 on 2021-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0015_auto_20210524_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_sliding',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
