# Generated by Django 2.2 on 2021-05-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0016_auto_20210524_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies_And_People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.TextField(max_length=150)),
                ('company_logo', models.ImageField(upload_to='photos/home')),
            ],
        ),
    ]
