# Generated by Django 2.2 on 2021-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0017_companies_and_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies_and_people',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companies_and_people',
            name='reviews',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
