# Generated by Django 2.2 on 2021-05-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0018_auto_20210524_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies_and_people',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='companies_and_people',
            name='is_available',
        ),
    ]
