# Generated by Django 2.2 on 2021-05-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0019_auto_20210524_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies_Logos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.TextField(blank=True, max_length=150)),
                ('logo', models.ImageField(upload_to='photos/home')),
            ],
        ),
    ]
