# Generated by Django 2.2 on 2021-05-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0021_auto_20210524_2054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apk_Areas',
            new_name='Application_Areas',
        ),
        migrations.AddField(
            model_name='media_sliding',
            name='know_more_hyperlink',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
