# Generated by Django 2.2 on 2021-05-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0022_auto_20210526_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_sliding',
            name='know_more_hyperlink',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
