# Generated by Django 2.2 on 2021-05-26 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0025_auto_20210526_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media_sliding',
            old_name='know_more_hyperlink_url',
            new_name='know_more_hyperlink',
        ),
        migrations.RemoveField(
            model_name='media_sliding',
            name='know_more_hyperlink_vedios',
        ),
    ]
