# Generated by Django 2.2 on 2021-05-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0026_auto_20210526_0920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlidingImage',
            new_name='I_SlidingImage',
        ),
        migrations.RenameModel(
            old_name='Quantity_Title',
            new_name='Ii_Quantity_Title',
        ),
        migrations.RenameModel(
            old_name='Application_Areas',
            new_name='Iii_Application_Areas',
        ),
        migrations.RenameModel(
            old_name='Media_Coverage',
            new_name='Iv_Media_Coverage',
        ),
        migrations.RenameModel(
            old_name='Media_Sliding',
            new_name='V_Media_Sliding',
        ),
        migrations.RenameModel(
            old_name='Companies_And_People',
            new_name='Vi_Companies_And_People',
        ),
        migrations.RenameModel(
            old_name='Companies_Logos',
            new_name='Vii_Companies_Logos',
        ),
    ]
