# Generated by Django 2.2 on 2021-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0002_aboutus_odd_even_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('progress_title', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('is_available', models.TextField(blank=True, max_length=400)),
            ],
        ),
    ]
