# Generated by Django 2.2 on 2021-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0003_company_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_progress',
            name='is_available',
            field=models.BooleanField(blank=True, max_length=400),
        ),
    ]
