# Generated by Django 2.2 on 2021-05-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0005_auto_20210526_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_progress',
            name='progress_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
