# Generated by Django 2.2 on 2021-05-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0006_company_progress_progress_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_progress',
            name='is_available',
        ),
    ]
