# Generated by Django 2.2 on 2021-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0007_remove_company_progress_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Working_Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(max_length=150)),
                ('steps', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('image', models.ImageField(upload_to='photos/about')),
                ('is_available', models.BooleanField()),
            ],
        ),
    ]
