# Generated by Django 2.2 on 2021-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0008_working_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_steps',
            name='heading',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='working_steps',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/about'),
        ),
    ]
