# Generated by Django 2.2 on 2021-05-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0009_auto_20210526_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='working_steps',
            name='even',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='working_steps',
            name='odd',
            field=models.BooleanField(default=False),
        ),
    ]
