# Generated by Django 2.2 on 2021-05-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0010_auto_20210526_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='working_steps',
            name='even',
        ),
        migrations.RemoveField(
            model_name='working_steps',
            name='odd',
        ),
    ]
