# Generated by Django 2.2 on 2021-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0011_auto_20210526_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='working_steps',
            old_name='description',
            new_name='description_right',
        ),
        migrations.RenameField(
            model_name='working_steps',
            old_name='steps',
            new_name='steps_right',
        ),
        migrations.AddField(
            model_name='working_steps',
            name='description_left',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='working_steps',
            name='steps_left',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
