# Generated by Django 2.2 on 2021-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0012_auto_20210526_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='photos/about')),
                ('name', models.TextField(blank=True, max_length=150)),
                ('profession', models.TextField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
