# Generated by Django 2.2 on 2021-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0013_team_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe_To_Our_Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/about')),
                ('description', models.TextField(max_length=150)),
            ],
        ),
    ]
