# Generated by Django 2.2 on 2021-05-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0014_subscribe_to_our_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus_odd_even_content',
            name='even',
        ),
        migrations.RemoveField(
            model_name='aboutus_odd_even_content',
            name='odd',
        ),
        migrations.AddField(
            model_name='aboutus_odd_even_content',
            name='push_image',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
