# Generated by Django 2.2 on 2021-05-29 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0015_auto_20210529_0838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Us_Top_Content',
            new_name='I_About_Us_Top_Content',
        ),
        migrations.RenameModel(
            old_name='Aboutus_Odd_Even_Content',
            new_name='II_Aboutus_Odd_Even_Content',
        ),
        migrations.RenameModel(
            old_name='Company_Progress',
            new_name='III_Company_Progress',
        ),
        migrations.RenameModel(
            old_name='Working_Steps',
            new_name='IV_Working_Steps',
        ),
        migrations.RenameModel(
            old_name='Team_Box',
            new_name='V_Team_Box',
        ),
        migrations.RenameModel(
            old_name='Subscribe_To_Our_Newsletter',
            new_name='VI_Subscribe_To_Our_Newsletter',
        ),
    ]
