# Generated by Django 2.2 on 2021-05-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0016_auto_20210529_0847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='I_About_Us_Top_Content',
            new_name='IAbout_Us_Top_Content',
        ),
    ]
