# Generated by Django 2.2 on 2021-05-29 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0017_auto_20210529_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='II_Aboutus_Odd_Even_Content',
            new_name='IIAboutus_Odd_Even_Content',
        ),
        migrations.RenameModel(
            old_name='III_Company_Progress',
            new_name='IIICompany_Progress',
        ),
        migrations.RenameModel(
            old_name='IV_Working_Steps',
            new_name='IVWorking_Steps',
        ),
        migrations.RenameModel(
            old_name='VI_Subscribe_To_Our_Newsletter',
            new_name='VISubscribe_To_Our_Newsletter',
        ),
        migrations.RenameModel(
            old_name='V_Team_Box',
            new_name='VTeam_Box',
        ),
    ]
