# Generated by Django 2.2 on 2021-05-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0018_auto_20210529_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IIAboutus_Odd_Even_Content',
            new_name='Ii_Aboutus_Odd_Even_Content',
        ),
    ]
