# Generated by Django 2.2 on 2021-05-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0019_auto_20210529_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IAbout_Us_Top_Content',
            new_name='I_About_Us_Top_Content',
        ),
        migrations.RenameModel(
            old_name='IIICompany_Progress',
            new_name='Iii_Company_Progress',
        ),
        migrations.RenameModel(
            old_name='IVWorking_Steps',
            new_name='Iv_Working_Steps',
        ),
        migrations.RenameModel(
            old_name='VTeam_Box',
            new_name='V_Team_Box',
        ),
        migrations.RenameModel(
            old_name='VISubscribe_To_Our_Newsletter',
            new_name='Vi_Subscribe_To_Our_Newsletter',
        ),
    ]
