# Generated by Django 2.2 on 2021-05-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0020_auto_20210529_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_team_box',
            name='hyperlink',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
